//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connected {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Connected.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string AccountingDomain {
            get {
                return ResourceManager.GetString("AccountingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string AssetsDomain {
            get {
                return ResourceManager.GetString("AssetsDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonDomain {
            get {
                return ResourceManager.GetString("CommonDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string CoreDomain {
            get {
                return ResourceManager.GetString("CoreDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CustomersDomain {
            get {
                return ResourceManager.GetString("CustomersDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DocumentsDomain {
            get {
                return ResourceManager.GetString("DocumentsDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Activator.CreateInstance method could not create a default instance of the supplied value type.
        /// </summary>
        public static string ErrActivatorCreateInstance {
            get {
                return ResourceManager.GetString("ErrActivatorCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type name.
        /// </summary>
        public static string ErrCannotResolveTypeName {
            get {
                return ResourceManager.GetString("ErrCannotResolveTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent access exception.
        /// </summary>
        public static string ErrConcurrent {
            get {
                return ResourceManager.GetString("ErrConcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create instance of type.
        /// </summary>
        public static string ErrCreateInstanceNull {
            get {
                return ResourceManager.GetString("ErrCreateInstanceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create queued dispatcher.
        /// </summary>
        public static string ErrCreateQueuedDispatcher {
            get {
                return ResourceManager.GetString("ErrCreateQueuedDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create service instance.
        /// </summary>
        public static string ErrCreateService {
            get {
                return ResourceManager.GetString("ErrCreateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value type contains generic parameters. Default value cannot be retrieved.
        /// </summary>
        public static string ErrDefaultGeneric {
            get {
                return ResourceManager.GetString("ErrDefaultGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create entity instance.
        /// </summary>
        public static string ErrEntityCreate {
            get {
                return ResourceManager.GetString("ErrEntityCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity expected.
        /// </summary>
        public static string ErrEntityExpected {
            get {
                return ResourceManager.GetString("ErrEntityExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is forbidden due to the entity protector..
        /// </summary>
        public static string ErrEntityProtection {
            get {
                return ResourceManager.GetString("ErrEntityProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not implement expected interface.
        /// </summary>
        public static string ErrInterfaceExpected {
            get {
                return ResourceManager.GetString("ErrInterfaceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string ErrInternalServerError {
            get {
                return ResourceManager.GetString("ErrInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interface specified.
        /// </summary>
        public static string ErrInvalidInterface {
            get {
                return ResourceManager.GetString("ErrInvalidInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot obtain lock.
        /// </summary>
        public static string ErrLock {
            get {
                return ResourceManager.GetString("ErrLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform merge.
        /// </summary>
        public static string ErrMergeNull {
            get {
                return ResourceManager.GetString("ErrMergeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not found.
        /// </summary>
        public static string ErrMethodNotFound {
            get {
                return ResourceManager.GetString("ErrMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property not found.
        /// </summary>
        public static string ErrPropertyNotFound {
            get {
                return ResourceManager.GetString("ErrPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not registered.
        /// </summary>
        public static string ErrServiceNotRegistered {
            get {
                return ResourceManager.GetString("ErrServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharding node does not exist.
        /// </summary>
        public static string ErrShardingNodeNotFound {
            get {
                return ResourceManager.GetString("ErrShardingNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value type is not a publicly-visible type. Default value cannot be retrieved.
        /// </summary>
        public static string ErrTypeInternal {
            get {
                return ResourceManager.GetString("ErrTypeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        public static string KnowledgeDomain {
            get {
                return ResourceManager.GetString("KnowledgeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        public static string LogisticsDomain {
            get {
                return ResourceManager.GetString("LogisticsDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string MaintenanceDomain {
            get {
                return ResourceManager.GetString("MaintenanceDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string ManufacturingDomain {
            get {
                return ResourceManager.GetString("ManufacturingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string MarketingDomain {
            get {
                return ResourceManager.GetString("MarketingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string PlanningDomain {
            get {
                return ResourceManager.GetString("PlanningDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsDomain {
            get {
                return ResourceManager.GetString("ProjectsDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string QualityDomain {
            get {
                return ResourceManager.GetString("QualityDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string ResourcesDomain {
            get {
                return ResourceManager.GetString("ResourcesDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string SalesDomain {
            get {
                return ResourceManager.GetString("SalesDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply.
        /// </summary>
        public static string SupplyDomain {
            get {
                return ResourceManager.GetString("SupplyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Antiforgery token.
        /// </summary>
        public static string ValAntiForgery {
            get {
                return ResourceManager.GetString("ValAntiForgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value.
        /// </summary>
        public static string ValDuplicate {
            get {
                return ResourceManager.GetString("ValDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity is disabled.
        /// </summary>
        public static string ValEntityDisabled {
            get {
                return ResourceManager.GetString("ValEntityDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value not defined.
        /// </summary>
        public static string ValEnumValueNotDefined {
            get {
                return ResourceManager.GetString("ValEnumValueNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value contains invalid character.
        /// </summary>
        public static string ValInvalidChars {
            get {
                return ResourceManager.GetString("ValInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string ValInvalidUser {
            get {
                return ResourceManager.GetString("ValInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum allowed value is {0}..
        /// </summary>
        public static string ValMinValue {
            get {
                return ResourceManager.GetString("ValMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value mismatch.
        /// </summary>
        public static string ValMismatch {
            get {
                return ResourceManager.GetString("ValMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must contain non default value.
        /// </summary>
        public static string ValNonDefault {
            get {
                return ResourceManager.GetString("ValNonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string ValNotFound {
            get {
                return ResourceManager.GetString("ValNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced record exists.
        /// </summary>
        public static string ValReference {
            get {
                return ResourceManager.GetString("ValReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script tag is not allowed.
        /// </summary>
        public static string ValScriptTagNotAllowed {
            get {
                return ResourceManager.GetString("ValScriptTagNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string ValUnauthorized {
            get {
                return ResourceManager.GetString("ValUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected.
        /// </summary>
        public static string ValValueExpected {
            get {
                return ResourceManager.GetString("ValValueExpected", resourceCulture);
            }
        }
    }
}
