using Connected.Storage.Schemas;
using System.Text;

namespace Connected.Storage.Oracle.Schemas;

/// <summary>
/// Adds a new column to an existing Oracle database table.
/// </summary>
/// <remarks>
/// This transaction generates and executes the ALTER TABLE ADD DDL statement for adding
/// a new column to a table. After adding the column, it handles additional operations such as
/// primary key constraint creation if specified in the column definition. Oracle supports
/// adding columns with default values and identity specifications (12c+) in a single ALTER TABLE
/// statement. For Oracle versions prior to 12c, identity behavior requires separate sequence and
/// trigger creation. The operation ensures that all column characteristics including constraints
/// are properly applied during the column addition process. Oracle automatically commits DDL
/// statements, so the operation cannot be rolled back. Column names are case-insensitive and
/// stored in uppercase unless quoted.
/// </remarks>
internal sealed class ColumnAdd(ISchemaColumn column)
	: ColumnTransaction(column)
{
	/// <inheritdoc/>
	protected override async Task OnExecute()
	{
		/*
		 * Execute the ALTER TABLE ADD statement to add the new column.
		 * Oracle uses ADD instead of ADD COLUMN syntax.
		 */
		await Context.Execute(CommandText);

		/*
		 * If the column is designated as a primary key, create the primary key constraint.
		 * Oracle allows only one primary key per table.
		 */
		if (Column.IsPrimaryKey)
			await new PrimaryKeyAdd(Column).Execute(Context);
	}

	/// <summary>
	/// Gets the DDL command text for adding the column.
	/// </summary>
	/// <value>
	/// The ALTER TABLE ADD statement with column definition.
	/// </value>
	/// <remarks>
	/// Oracle ALTER TABLE ADD syntax differs from PostgreSQL by omitting the COLUMN keyword.
	/// Oracle 12c+ supports GENERATED BY DEFAULT AS IDENTITY for auto-increment columns.
	/// </remarks>
	private string CommandText
	{
		get
		{
			var text = new StringBuilder();

			text.Append($"ALTER TABLE {Escape(Context.Schema.Schema, Context.Schema.Name)} ");
			text.Append($"ADD {CreateColumnCommandText(Column)}");

			return text.ToString();
		}
	}
}
