namespace Connected.Storage.Oracle.Schemas;

/// <summary>
/// Represents identity column configuration for an Oracle database table.
/// </summary>
/// <remarks>
/// This class encapsulates metadata about identity columns and their associated sequences.
/// Oracle 12c+ supports GENERATED AS IDENTITY syntax for automatic identity columns, which
/// internally creates a sequence. For earlier Oracle versions, identity behavior is manually
/// implemented using sequences and triggers. This class captures identity configuration
/// regardless of implementation method, storing sequence name, increment value, and seed value.
/// Identity column information is retrieved from ALL_TAB_IDENTITY_COLS (12c+) or by querying
/// sequences and triggers for earlier versions.
/// </remarks>
internal sealed class ObjectIdentity
{
	/// <summary>
	/// Gets or sets the name of the column defined as identity.
	/// </summary>
	/// <value>
	/// The column name, typically the primary key column.
	/// </value>
	/// <remarks>
	/// Oracle tables can have at most one identity column, which is typically the primary key.
	/// Identity columns are marked with IDENTITY_COLUMN = 'YES' in ALL_TAB_COLUMNS (12c+).
	/// </remarks>
	public required string ColumnName { get; set; }

	/// <summary>
	/// Gets or sets the sequence name used for identity value generation.
	/// </summary>
	/// <value>
	/// The sequence name, or <c>null</c> for GENERATED AS IDENTITY columns where Oracle manages the sequence.
	/// </value>
	/// <remarks>
	/// For GENERATED AS IDENTITY columns (12c+), Oracle creates a system-named sequence automatically.
	/// For manual implementations (pre-12c), this property stores the explicitly created sequence name.
	/// Sequence names follow the same naming rules as other Oracle objects (30 or 128 character limit).
	/// </remarks>
	public string? SequenceName { get; set; }

	/// <summary>
	/// Gets or sets the increment value for the sequence.
	/// </summary>
	/// <value>
	/// The value by which the sequence increments with each NEXTVAL call, typically 1.
	/// </value>
	/// <remarks>
	/// Oracle sequences can increment by any positive or negative integer value. The default
	/// and most common value is 1. This value is retrieved from ALL_SEQUENCES.INCREMENT_BY column.
	/// </remarks>
	public int Increment { get; set; } = 1;

	/// <summary>
	/// Gets or sets the starting seed value for the sequence.
	/// </summary>
	/// <value>
	/// The initial value of the sequence, typically 1.
	/// </value>
	/// <remarks>
	/// The seed value determines where the sequence begins generating values. Oracle stores
	/// this as MIN_VALUE and LAST_NUMBER in ALL_SEQUENCES. For GENERATED AS IDENTITY columns,
	/// START WITH can be specified explicitly, otherwise defaults to 1.
	/// </remarks>
	public long Seed { get; set; } = 1;

	/// <summary>
	/// Gets or sets a value indicating whether the identity column is generated always or by default.
	/// </summary>
	/// <value>
	/// <c>true</c> if GENERATED ALWAYS; <c>false</c> if GENERATED BY DEFAULT.
	/// </value>
	/// <remarks>
	/// GENERATED ALWAYS prevents explicit value insertion, always using the sequence.
	/// GENERATED BY DEFAULT allows explicit values to be inserted, using the sequence only
	/// when no value is provided. This property is retrieved from ALL_TAB_IDENTITY_COLS.GENERATION_TYPE
	/// (12c+).
	/// </remarks>
	public bool GeneratedAlways { get; set; }
}
